
# FROM python:3.12
# WORKDIR /backend/app
# COPY backend/app/requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
# COPY backend/app/ .
# EXPOSE 8000
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

FROM python:3.12
WORKDIR /backend/app
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app/ .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
