# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#         - name: backend
#           image: nandeesh151/backend_recipe2
#           ports:
#             - containerPort: 8000  
#           env:
#             - name: SECRET_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: my-secrets
#                   key: SECRET_KEY
#             - name: DATABASE_URL
#               valueFrom:
#                 secretKeyRef:
#                   name: my-secrets
#                   key: DATABASE_URL

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2  # Increased replicas for high availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # Maximum number of pods that can be unavailable during the update
      maxSurge: 1        # Maximum number of pods that can be created over the desired number of pods
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nandeesh151/backend_recipe2
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DATABASE_URL
  
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer  