apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000  # Exposes port 8000 internally
      targetPort: 8000  # The target port inside the backend container
  type: ClusterIP