apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  SECRET_KEY: NWJjN2M1MGI0MjRiNjU4YjcxOWNhMjdjNzYyMzNmYTJiNzg0NTgxMjRhYjU0YjIwMDdhMjgzMDhmN2IzNTFlYg== 
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vbmFuZGVlc2g6bmFuZGVlc2gxMjNAZGF0YWJhc2UtMS5jeG0yb21vZ2E0cjYudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvcmVjaXBlZmluZA==
  API_KEY: YzI5MjdhNmYxYTA2NGE4ZmE0NzFlMzFkNGQ0NjI2OWY=